name: C CI

on: [push, pull_request]

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
      CXX: g++
      CXXFLAGS: -Werror -Wall -pedantic
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/build

  ubuntu22:
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
      CXXFLAGS: -Werror -Wall -pedantic
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/build

  ubuntu22-clang:
    runs-on: ubuntu-22.04
    env:
      CC: clang-12
      CXX: clang++-12
      CXXFLAGS: -Werror -Wall -pedantic
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/build

  ubuntu22-release:
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
      # disabled array-bounds warning because it is triggered by code generated by the protoc compiler
      CXXFLAGS: -Werror -Wall -pedantic -Wno-array-bounds
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-ubuntu
      - uses: ./.github/actions/build

  ubuntu22-make:
    runs-on: ubuntu-22.04
    env:
      CC: gcc
      CXX: g++
      CXXFLAGS: -Werror -Wall -pedantic
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-ubuntu
      - run: make -C src

  macos:
    runs-on: macos-latest
    env:
      CC: clang
      CXX: clang++
      CXXFLAGS: -Werror -Wall -pedantic -std=c++17
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-macos
      - uses: ./.github/actions/build

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-windows
      - uses: ./.github/actions/build-windows

